// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/products-admin/ActivityFeed.tsx": () => import("../components/mockups/products-admin/ActivityFeed.tsx"),
  "./components/mockups/products-admin/MetricsFirst.tsx": () => import("../components/mockups/products-admin/MetricsFirst.tsx"),
  "./components/mockups/products-admin/PortfolioGrid.tsx": () => import("../components/mockups/products-admin/PortfolioGrid.tsx"),
  "./components/mockups/products-admin/SplitNavigator.tsx": () => import("../components/mockups/products-admin/SplitNavigator.tsx")
};
